DROP TABLE LIB_MEMBER CASCADE CONSTRAINTS;
DROP TABLE LIB_BOOK CASCADE CONSTRAINTS;
DROP TABLE LIB_RENT CASCADE CONSTRAINTS;
DROP TABLE LIB_RENTLOG CASCADE CONSTRAINTS;
DROP TABLE LIB_BOOK_REQUEST CASCADE CONSTRAINTS;
DROP TABLE LIB_BOOK_REVIEW CASCADE CONSTRAINTS;
DROP TABLE LIB_REVIEW_REPLE CASCADE CONSTRAINTS;

DROP SEQUENCE LIB_RENT_SEQ;
DROP SEQUENCE LIB_RENTLOG_SEQ;
DROP SEQUENCE LIB_REVIEW_SEQ;
DROP SEQUENCE LIB_BOOK_REQUEST_SEQ;

CREATE TABLE LIB_MEMBER(
	ID VARCHAR2(30) CONSTRAINT PK_ID PRIMARY KEY, -- 회원 아이디
	PW VARCHAR2(30) NOT NULL,								 -- 회원 비밀번호
	NAME VARCHAR2(30) NOT NULL,							   -- 회원 이름
	PHONE VARCHAR2(20) CONSTRAINT UK_PHONE UNIQUE,		   -- 회원 전화번호
	RENTCOUNT NUMBER(2) NOT NULL,							 -- 빌린 책의 갯수
	BOOKINGCOUNT NUMBER(2) NOT NULL,							 -- 빌린 책의 갯수
	AUTH NUMBER(1)	NOT NULL									-- 권한
);

insert into LIB_MEMBER values('admin', 'admin', '김사서', '010-0987-6543', 0,0,1);

CREATE TABLE "HR"."LIB_BOOK"(
	"ISBN" VARCHAR2(30 BYTE),
	"LOCATION" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"TITLE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"TYPE" VARCHAR2(30 BYTE) NOT NULL ENABLE,
	"PUBLISHER" VARCHAR2(30 BYTE) NOT NULL ENABLE,
	"AUTHOR" VARCHAR2(30 BYTE) NOT NULL ENABLE,
	"IMG" VARCHAR2(100 BYTE),
	"INFO" VARCHAR2(2000 BYTE),
	"RENT_STATE" VARCHAR2(30 BYTE) NOT NULL ENABLE,
	"BOOKING_ID" VARCHAR2(30 BYTE),

	CONSTRAINT "PK_ISBN" PRIMARY KEY ("ISBN"),
	CONSTRAINT FK_BOOKING_ID FOREIGN KEY(BOOKING_ID) REFERENCES LIB_MEMBER(ID)   -- 예약한 회원아이디
);

CREATE SEQUENCE LIB_RENT_SEQ
INCREMENT BY 1
START WITH 1;

CREATE TABLE LIB_RENT(
	RENT_INDEX NUMBER(5) CONSTRAINT PK_RENT_INDEX PRIMARY KEY,
	ISBN VARCHAR2(30) NOT NULL,	  -- 대여중인 도서
	ID VARCHAR2(30) NOT NULL,		-- 대여한 회원
	RENT_DATE DATE NOT NULL,	 -- 대여 상태
	RETURN_DATE  DATE NOT NULL,  -- 반납 예정일

	CONSTRAINT FK_ISBN FOREIGN KEY(ISBN) REFERENCES LIB_BOOK(ISBN),	-- 대여중인 도서
	CONSTRAINT FK_ID FOREIGN KEY(ID) REFERENCES LIB_MEMBER(ID)		-- 대여한 회원아이디
);

CREATE SEQUENCE LIB_RENTLOG_SEQ
INCREMENT BY 1
START WITH 1;

CREATE TABLE LIB_RENTLOG(
	LOG_INDEX NUMBER(5) CONSTRAINT PK_LOG_INDEX PRIMARY KEY,
	ISBN VARCHAR2(30) NOT NULL,
	ID VARCHAR2(30) NOT NULL,                                -- 대여한 회원아이디
	RENT_STATE VARCHAR(30) NOT NULL,
	RENT_DATE DATE NOT NULL,                                 -- 대여일
	RETURN_DATE DATE,                                        -- 반납일

	CONSTRAINT FK_ID_LOG FOREIGN KEY(ID) REFERENCES LIB_MEMBER(ID) -- 대여/반납한 회원
);

CREATE SEQUENCE LIB_REVIEW_SEQ
INCREMENT BY 1
START WITH 1;

CREATE TABLE LIB_BOOK_REVIEW(
	REVIEW_INDEX NUMBER(5) CONSTRAINT PK_REVIEW_INDEX PRIMARY KEY,
	ISBN VARCHAR2(30) NOT NULL,
	ID VARCHAR2(30) NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(2000),
	WRITE_DATE DATE NOT NULL,
	RATE NUMBER(1) NOT NULL,

	CONSTRAINT FK_ISBN_REVIEW FOREIGN KEY(ISBN) REFERENCES LIB_BOOK(ISBN),
	CONSTRAINT FK_ID_REVIEW FOREIGN KEY(ID) REFERENCES LIB_MEMBER(ID)
);

CREATE TABLE "HR"."LIB_BOOK_REQUEST"(
	"REQUEST_INDEX" NUMBER(5,0),
	"TITLE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"TYPE" VARCHAR2(30 BYTE) NOT NULL ENABLE,
	"PUBLISHER" VARCHAR2(30 BYTE) NOT NULL ENABLE,
	"AUTHOR" VARCHAR2(30 BYTE) NOT NULL ENABLE,
	"ID" VARCHAR2(30 BYTE) NOT NULL ENABLE,
	"REQUEST_DATE" DATE NOT NULL ENABLE,
	"STATE" VARCHAR2(30 BYTE) NOT NULL ENABLE,

	 CONSTRAINT "FK_ID_BOOK_REQUEST" FOREIGN KEY ("ID")
	 REFERENCES "HR"."LIB_MEMBER" ("ID") ENABLE
);
CREATE SEQUENCE LIB_BOOK_REQUEST_SEQ INCREMENT BY 1 START WITH 1;

CREATE TABLE LIB_REVIEW_REPLE(
	REVIEW_INDEX NUMBER(5) NOT NULL,											  -- 원본 글 INDEX
	ID VARCHAR2(30) NOT NULL,											-- 댓글을 작성한 id
	CONTENT VARCHAR(100) NOT NULL,									   -- 댓글
	WRITE_DATE DATE NOT NULL,											-- 작성 date
	GRP NUMBER(5) NOT NULL,
	STEP NUMBER(5) NOT NULL,
	DEPTH NUMBER(1) NOT NULL,											-- DEPTH

	CONSTRAINT FK__REPLE FOREIGN KEY(ID) REFERENCES LIB_MEMBER(ID), -- 대여/반납한 회원
	CONSTRAINT FK_REPLE_REVIEW_INDEX FOREIGN KEY(REVIEW_INDEX) REFERENCES LIB_BOOK_REVIEW(REVIEW_INDEX)
);
